import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { Header } from "~/components/Header";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Docs Wrapper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: docs, refetch: refetchDocs } = api.doc.getAll.useQuery(
    undefined, //no input
    {
      enabled: sessionData?.user !== undefined,
    }
  );

  const createDoc = api.doc.create.useMutation({
    onSuccess: () => {
      void refetchDocs();
    },
  });
  return (
    <div className="">
      {sessionData?.user ? (
        <div className="md:container md:mx-auto">
          <input
            type="text"
            placeholder="Type docs title here..."
            className="input-bordered input w-full max-w-xs bg-gray-100"
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                console.log("createDoc.mutate", createDoc.mutate);
                createDoc.mutate({
                  title: e.currentTarget.value,
                });
                e.currentTarget.value = "";
              }
            }}
          />
          <div className="divider"></div>
          <div className="px-2 ">
            <h1 className="text-2xl font-bold">Docs</h1>
            <ul className=" space-y-2 bg-black py-4">
              {docs &&
                docs?.map((doc) => (
                  <li className="w-full" key={doc.id}>
                    <a
                      className="w-full rounded-md bg-gray-100 p-2"
                      href="#"
                      onClick={(evt) => {
                        evt.preventDefault();
                      }}
                    >
                      {doc.title}
                    </a>
                  </li>
                ))}
            </ul>
          </div>
        </div>
      ) : (
        <div
          className="hero min-h-screen"
          style={{
            backgroundImage: `url("https://cdn.pixabay.com/photo/2016/11/22/23/03/hardwood-1851071_960_720.jpg")`,
          }}
        >
          <div className="hero-overlay bg-opacity-60"></div>
          <div className="hero-content text-center text-neutral-content">
            <div className="max-w-md">
              <h1 className="mb-5 text-5xl font-bold">Hello there</h1>
              <p className="mb-5">
                Provident cupiditate voluptatem et in. Quaerat fugiat ut
                assumenda excepturi exercitationem quasi. In deleniti eaque aut
                repudiandae et a id nisi.
              </p>
              <button className="btn-primary btn">Get Started</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
